### PR TITLE
First batch of forcing linear into textures

### PR DESCRIPTION
**Pull request by AmyRoxwell**
For the most part, we want people to use nearest as a game config for FU/FUcomplete, allowing you to see the additional detail without looking blurry, but certain textures (like skyboxes, GFX or smoke) don't play nice with it or look way too pixelated (lighting and shadows suffer a lot from this).

Thanks to PPSSPP Filtering feature on it's texture replacement, we can force linear on said textures so they look great without making the whole game look blurry!

(only village atm cuz there are lot more textures that need linear, like monster dust particles)

Old:
Screenshot_02262024_105818
Screenshot_02262024_105800
Screenshot_02262024_105751
Screenshot_02262024_105743

New:
Screenshot_02262024_105603
Screenshot_02262024_105639
Screenshot_02262024_104939
Screenshot_02262024_105655

### CODE REVIEW

**Comment by Monkbreh** [comment]
>  we want people to use nearest as a game config for FU/FUcomplete, allowing you to see the additional detail without looking blurry, but certain textures (like skyboxes, GFX or smoke) don't play nice with it or look way too pixelated (lighting and shadows suffer a lot from this).

Lookin great, tho id imagine most folks would prefer the game on linear since most people may be playing on higher resolutions. Eitherway it should be optional with this setup.

**Comment by AmyRoxwell** [comment]
> Lookin great, tho id imagine most folks would prefer the game on linear since most people may be playing on higher resolutions. Eitherway it should be optional with this setup.

If that's the plan, then I will focus on just making filters for stuff that requires linear only, that way both auto/linear and nearest folks have a great experience with the texture pack

**Comment by Monkbreh** [comment]
Yeah, its the more efficient route i guess since you wont have to deal with identifying many textures. One can just enable nearest filtering globally without affecting stuff like smoke, skyboxes etc

**Comment by AmyRoxwell** [comment]
> Yeah, its the more efficient route i guess since you wont have to deal with identifying many textures. One can just enable nearest filtering globally without affecting stuff like smoke, skyboxes etc

Right! easier for us and the user >:D!

**Pull request merged**
